### ISSUE TITLE
AppImage won't run anymore on Ubuntu 20.04

### ISSUE THREAD

**Issue by chdiza** [clickot/ungoogled-chromium-build#4]
I'm not sure this is the right place to report this issue.  I'm running the AppImage found [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/114.0.5735.106-1), previous versions of which have been running great on Ubuntu 20.04.

But the version in that link won't run at all.  Instead I see:
```
/home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome)
/home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome)
/home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome)
/home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/chdiza/.tmp/tmpdir/.mount_chrominAEQcq/opt/google/chrome/chrome)
```

I hope this is unintentional.  I find it hard to believe that Ubuntu 20.04 would be too old to run a chromium AppImage.  But if I'm understanding those error messages correctly, the glibc on this machine is not "new enough".

Can the ability to run on Ubuntu 20.04 be restored?

**Comment by clickot** [comment]
hi @chdiza ,see https://github.com/ungoogled-software/ungoogled-chromium/issues/2001#issuecomment-1597463689 . The thing is that the chromium code does not compile anymore when using an older version of gclib, and my tries to patch this failed. I switched to a new builder image (debian bookworm instead of bullseye), but that leads to the error above on ubuntu 20.04. The image runs fine under ubuntu 22.04, so maybe you might consider upgrading. 
What you also might do is to try ungoogled chromium as flatpak which is available at flathub.org. flatpak's don't rely on glibc on the host system.

**Comment by chdiza** [comment]
@clickot Thanks for the reply.  The flatpak doesn't work either on 20.04, but for an apparently different reason.  This means the choices on 20.04 are to either use the snap or not use chromium.  The VAAPI AppImage doesn't work either because the libva version is too old on Ubuntu 20.04.

I know it's not your fault that upstream chromium now needs a newer glibc, and I thank you for your kind reply.

Now I get to wrestle with Debian or Mint.  At least chromium can just be apt-installed there.

**Comment by chdiza** [comment]
FYI, here's why the flatpak version of Ungoogled Chromium doesn't work on 20.04:
```
Failed to install com.github.Eloston.UngoogledChromium: app/com.github.Eloston.UngoogledChromium/x86_64/stable needs a later flatpak version (1.8.2)
```
This is absurd.  There's no point to flatpaks if packagers are going to demand recent enough versions of flatpak to cutoff LTS distros.

**Comment by chdiza** [comment]
(BTW my ire wasn't directed at you in the last comment.  Upstream chromium's flatpak has exactly the same issue.)

**Comment by gollum-z** [comment]
@chdiza In order to get the Flatpak UngoogledChromium to run you have to update Flatpak and eventually install `xdg-desktop-portal` on your machine. I did both (now Flatpak 1.14.4) and the browser is working here on Ubuntu 20.04.6

**Comment by chdiza** [comment]
@gollum-z Thanks, but I don't understand what "update Flatpak" could mean.  The flatpak version for Ubuntu 20.04 is `1.6.5-0ubuntu0.4`, according to `apt show flatpak`.

**Comment by gollum-z** [comment]
@chdiza Ubuntu ships and maintains often quite old software packages, so with Flatpak. I forgot to mention that a recent version can be obtained via the official Flatpak-PPA: see [https://flatpak.org/setup/Ubuntu](url). After adding the PPA you will get the version 1.14.4.
To list all installed packages and runtime(s) on your machine run `flatpak list` . The runtime (in the list called `GNOME Application Platform version 43     org.gnome.Platform`) is the "core" on which Flatpak relies and runs on.
Run `flatpak update`, the software will show you a list of packages installed on your system which can be updated. The Flatpak runtime itselt gets its updates in the same way. The most recent runtime is version 44 but there can also be a parallel installed version 43 (so in my case). After your confirmation flatpak will download the updates and install them on your system.

**Comment by chdiza** [comment]
@gollum-z Thanks, that's very helpful!

**Comment by gollum-z** [comment]
@chdiza You’re welcome!

**Comment by nicolaasjan** [comment]
The binary for Portable Linux 64-bit `114.0.5735.198-1` doesn't run either (on Linux Mint 20.3).
But why do I have no issue with the official Chromium Dev build `117.0.5862.0 `?

(flatpak is not an option here, because I'm running out of disk space...)
