### ISSUE TITLE
Sites stopped working.

### ISSUE THREAD

**Issue by h4ckee** [clickot/ungoogled-chromium-build#5]
Hi Guys.
A few releases ago, I ran into a problem on a couple of sites that were working earlier. I have tested them with other browsers (thorium and firefox) and there they work as expected.

When I try to login https://aliexpress.ru a window pops up saying: "Sorry, we have detected unusual traffic from your network. Please slide to verify." It doesn't matter how many times you slide the button it reappears again and again.
When I try to login https://lk.mts.ru, site says:
403 Error
Forbidden
Access to login.mts.ru is forbidden.
Try accessing the site login.mts.ru later or contact administration of the site.

Version 116.0.5845.96 (Official Build, ungoogled-chromium) AXE (64-bit)
Best regards.

**Comment by clickot** [comment]
i guess that this is rather a problem with ungoogled-chromium itself, not of my build of it, so i suppose you should place this issue in the ungoogled-software/ungoogled-chromium repository.

**Comment by h4ckee** [comment]
I used this binary - https://github.com/clickot/ungoogled-chromium-binaries/releases/download/116.0.5845.96-1/ungoogled-chromium_116.0.5845.96-1.1_linux.tar.xz
Isn't it yours?

**Comment by clickot** [comment]
it is, but i only compile and build the package of the code that the ungoogled-chromium guys deliver:
https://github.com/ungoogled-software/ungoogled-chromium

**Comment by h4ckee** [comment]
I've already created an issue here https://github.com/ungoogled-software/ungoogled-chromium-binaries/issues/434 and here https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/145
They said it's not theirs.

**Comment by clickot** [comment]
- https://github.com/ungoogled-software/ungoogled-chromium contains patches for the original chromium code to eliminate google's proprietary stuff
- https://github.com/ungoogled-software/ungoogled-chromium-binaries contains the web page with the downloads for the several builds of ungoogled-chromium for different platforms, meaning the chromium code patched by ungoogled-chromium patches compiled and packed for linux, windows,..
- the ungoogled-chromium-archlinux/windows/portablelinux etc repositories are projects where people maintain different platform builds.

So, when ungoogled-chromium does not work properly, then it is very likely that the problem is with chromium and it's patches provided by ungoogled-chromium repo. So the issue should be placed there.

I hope that clarifies the situation. I don't know how i could fix the problem you reported.

**Comment by h4ckee** [comment]
OK. Thank you.

**Comment by PF4Public** [comment]
@clickot Do you add "AXE" to version string? Something tells me that this binary isn't yours either.

**Comment by clickot** [comment]
@PF4Public I don't add anything the version string. Where do you see that "AXE"? This is what i see from my appimage:
![image](https://github.com/clickot/ungoogled-chromium-build/assets/89262220/fa5e7edb-fe4d-4380-915f-e5e4f25bd9e2)
 
Ahhhh i see, it's the version h4kee reported :-) ..

**Comment by PF4Public** [comment]
>Version 116.0.5845.96 (Official Build, ungoogled-chromium) AXE (64-bit)

@h4ckee Your binary is none of ours. You should first identify the source where you've obtained this binary from and file this issue there, we cannot fix an issue with the binary unrelated to us. And it is the thing I told you right from the start.

>Ahhhh i see, it's the version h4kee reported :-) ..

Exactly! I spotted this from the beginning!

**Comment by clickot** [comment]
@h4ckee you can download our binaries [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) or [here](https://github.com/clickot/ungoogled-chromium-binaries/releases)

**Comment by h4ckee** [comment]
AXE is my hostname:
`> hostname`
`AXE`

The binary that I use:
[https://github.com/clickot/ungoogled-chromium-binaries/releases/download/116.0.5845.96-1/ungoogled-chromium_116.0.5845.96-1.1_linux.tar.xz](https://github.com/clickot/ungoogled-chromium-binaries/releases/download/116.0.5845.96-1/ungoogled-chromium_116.0.5845.96-1.1_linux.tar.xz)

**Comment by PF4Public** [comment]
@h4ckee Have you had issues with 115?

**Comment by h4ckee** [comment]
yes. several releases ago I didn't, but don't remember how many.
